name: CI

on:
  push:
  pull_request:
    branches: [main]

jobs:
  lint:
    name: ESLint and TypeScript Checks
    runs-on: ubuntu-latest
    steps:
      - uses: pnpm/action-setup@v2
        with:
          version: 8
      - name: Setup Node.js 18
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: "pnpm"

      - name: Install dependencies
        run: pnpm install
      - name: Build project
        run: pnpm build
